cargo-features = ["workspace-inheritance"]
[package]
name = "mars-core"
version = "1.0.2"
authors = ["Spike Spiegel <spikeonmars@protonmail.com>"]
edition = "2018"
description = "Mars is a fully automated, on-chain credit protocol built on Terra and governed by a decentralised community of users and developers"
license = "GPL-3.0"
repository = "https://github.com/mars-protocol/mars-core"
homepage = "https://marsprotocol.io"
documentation = "https://docs.marsprotocol.io/mars-protocol/developers/protocol-overview"
readme = "README.md"
keywords = ["terra", "cosmwasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]

cw2 = { workspace = true }
cw20= { workspace = true }
cw20-base = { worksapce = true, features = ["library"] }

cosmwasm-std = { workspace = true }

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.23"

terraswap = {workspace = true}


[profile.release]
overflow-checks = true
